"""fase4: tambah is_anomaly dan anomaly_z_score ke check_results

Revision ID: 06cc9ff08961
Revises: e2ca027c666d
Create Date: 2026-09-07 01:31:15.836027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06cc9ff08961'
down_revision: Union[str, Sequence[str], None] = 'e2ca027c666d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('check_results', sa.Column('is_anomaly', sa.Boolean(), nullable=False))
    op.add_column('check_results', sa.Column('anomaly_z_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('check_results', 'anomaly_z_score')
    op.drop_column('check_results', 'is_anomaly')
    # ### end Alembic commands ###
