"""fase3: tambah check_type, tcp_port, expected_content ke monitor_targets

Revision ID: e2ca027c666d
Revises: d7f4d263cf88
Create Date: 2026-09-01 05:43:34.580044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2ca027c666d'
down_revision: Union[str, Sequence[str], None] = 'd7f4d263cf88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_targets', sa.Column('check_type', sa.String(length=20), nullable=False))
    op.add_column('monitor_targets', sa.Column('tcp_port', sa.Integer(), nullable=True))
    op.add_column('monitor_targets', sa.Column('expected_content', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_targets', 'expected_content')
    op.drop_column('monitor_targets', 'tcp_port')
    op.drop_column('monitor_targets', 'check_type')
    # ### end Alembic commands ###
